spring:
  application:
    name: apigw
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

server:
  port: 9100

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    persist-authorization: true
    urls:
      - name: API Gateway Service
        url: /v3/api-docs
      - name: Order Service
        url: /v3/api-docs/order-service
      - name: Product Service
        url: /v3/api-docs/product-service