spring:
  application:
    name: product-service
server:
  port: 0
  servlet:
    context-path: /api

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true